import { task } from "./Library/Interfaces";

export const data: task[] = [
    {
        id: 101,
        name: "Design Dicussion",
        description: "discuss design options",
        endDate: new Date("12/07/2021").toUTCString(),
        // repeat: {
        //     mon: true,
        //     tues: true,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 102,
        name: "Grooming First Sketches",
        description: "groom",
        endDate: new Date("12/08/2021").toUTCString(),
        // repeat: {
        //     mon: true,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: true,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 103,
        name: "Development Planning",
        description: "discuss planning options",
        endDate: new Date("12/09/2021").toUTCString(),
        // repeat: {
        //     mon: false,
        //     tues: true,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: true,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 104,
        name: "Food shopping",
        description: "go shopping for food",
        endDate: new Date("12/10/2021").toUTCString(),
        // repeat: {
        //     mon: true,
        //     tues: false,
        //     wed: false,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 105,
        name: "doctors appointment",
        description: "visit doctors about that thing",
        endDate: new Date("12/11/2021").toUTCString(),
        // repeat: {
        //     mon: false,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 106,
        name: "say hi to dave",
        description: "dave",
        endDate: new Date("12/12/2021").toUTCString(),
        // repeat: {
        //     mon: false,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
];
