import { task } from "./Library/Interfaces";

export const data: task[] = [
    {
        id: 101,
        name: "Design Dicussion",
        description: "discuss design options",
        endDate: new Date("11/22/2021").setDate(22),
        // repeat: {
        //     mon: true,
        //     tues: true,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 102,
        name: "Grooming First Sketches",
        description: "groom",
        endDate: new Date("11/23/2021").setDate(23),
        // repeat: {
        //     mon: true,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: true,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 103,
        name: "Development Planning",
        description: "discuss planning options",
        endDate: new Date("11/24/2021").setDate(24),
        // repeat: {
        //     mon: false,
        //     tues: true,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: true,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 104,
        name: "Food shopping",
        description: "go shopping for food",
        endDate: new Date("11/25/2021").setDate(25),
        // repeat: {
        //     mon: true,
        //     tues: false,
        //     wed: false,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 105,
        name: "doctors appointment",
        description: "visit doctors about that thing",
        endDate: new Date("11/26/2021").setDate(26),
        // repeat: {
        //     mon: false,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
    {
        id: 106,
        name: "say hi to dave",
        description: "dave",
        endDate: new Date("11/27/2021").setDate(27),
        // repeat: {
        //     mon: false,
        //     tues: false,
        //     wed: true,
        //     thurs: false,
        //     fri: false,
        //     sat: false,
        //     sun: false,
        // },
        // category: { id: 1, name: "task", colour: "fff" },
    },
];
